import type { AppTheme } from "@/types";

export type ThemeMode = "dark" | "light";
export type ThemeCategory = "dark" | "light" | "colorful" | "premium";

export interface ThemeDefinition {
  description: string;
  id: AppTheme;
  name: string;
  mode: ThemeMode;
  category: ThemeCategory;
  colors: {
    background: string;
    surface: string;
    surface2: string;
    border: string;
    text: string;
    muted: string;
    primary: string;
    success: string;
    warning: string;
    danger: string;
  };
}

export const DEFAULT_THEME_ID: AppTheme = "command_dark";

export const APP_THEMES: ThemeDefinition[] = [
  {
    id: "command_dark",
    name: "Command Dark",
    description: "Varsayilan koyu operasyon temasi.",
    mode: "dark",
    category: "dark",
    colors: {
      background: "#09090b",
      surface: "#111113",
      surface2: "#18181b",
      border: "#27272a",
      text: "#f4f4f5",
      muted: "#a1a1aa",
      primary: "#8b5cf6",
      success: "#22c55e",
      warning: "#f59e0b",
      danger: "#ef4444",
    },
  },
  {
    id: "midnight_violet",
    name: "Midnight Violet",
    description: "Daha mor, premium ve modern gorunum.",
    mode: "dark",
    category: "colorful",
    colors: {
      background: "#070514",
      surface: "#100b22",
      surface2: "#1b1235",
      border: "#34245f",
      text: "#f5f3ff",
      muted: "#c4b5fd",
      primary: "#a855f7",
      success: "#34d399",
      warning: "#fbbf24",
      danger: "#fb7185",
    },
  },
  {
    id: "obsidian_gold",
    name: "Obsidian Gold",
    description: "Siyah-altin yönetici paneli hissi.",
    mode: "dark",
    category: "premium",
    colors: {
      background: "#080706",
      surface: "#12100d",
      surface2: "#1c1710",
      border: "#3a2f1c",
      text: "#faf7ed",
      muted: "#c9b99a",
      primary: "#d4af37",
      success: "#22c55e",
      warning: "#f59e0b",
      danger: "#ef4444",
    },
  },
  {
    id: "slate_blue",
    name: "Slate Blue",
    description: "Daha kurumsal, soguk ve sade tema.",
    mode: "dark",
    category: "dark",
    colors: {
      background: "#0f172a",
      surface: "#111827",
      surface2: "#1e293b",
      border: "#334155",
      text: "#f8fafc",
      muted: "#94a3b8",
      primary: "#38bdf8",
      success: "#22c55e",
      warning: "#f59e0b",
      danger: "#f43f5e",
    },
  },
  {
    id: "executive_light",
    name: "Executive Light",
    description: "Gunduz kullanımi icin sade yönetici gorunumu.",
    mode: "light",
    category: "light",
    colors: {
      background: "#f8fafc",
      surface: "#ffffff",
      surface2: "#f1f5f9",
      border: "#cbd5e1",
      text: "#0f172a",
      muted: "#64748b",
      primary: "#4f46e5",
      success: "#16a34a",
      warning: "#d97706",
      danger: "#dc2626",
    },
  },
  {
    id: "emerald_terminal",
    name: "Emerald Terminal",
    description: "Siyah-yesil terminal ve hacker tarzi operasyon temasi.",
    mode: "dark",
    category: "colorful",
    colors: {
      background: "#020604",
      surface: "#07110c",
      surface2: "#0b1f14",
      border: "#164e2e",
      text: "#ecfdf5",
      muted: "#86efac",
      primary: "#22c55e",
      success: "#4ade80",
      warning: "#facc15",
      danger: "#f87171",
    },
  },
  {
    id: "cyber_neon",
    name: "Cyber Neon",
    description: "Neon mavi ve mor, modern teknoloji gorunumu.",
    mode: "dark",
    category: "colorful",
    colors: {
      background: "#050816",
      surface: "#0b1026",
      surface2: "#121a3d",
      border: "#263b80",
      text: "#eef2ff",
      muted: "#93c5fd",
      primary: "#06b6d4",
      success: "#10b981",
      warning: "#f59e0b",
      danger: "#fb7185",
    },
  },
  {
    id: "crimson_ops",
    name: "Crimson Ops",
    description: "Koyu kirmizi operasyon ve kriz yönetimi temasi.",
    mode: "dark",
    category: "colorful",
    colors: {
      background: "#0b0305",
      surface: "#16070a",
      surface2: "#240b10",
      border: "#4c121d",
      text: "#fff1f2",
      muted: "#fda4af",
      primary: "#e11d48",
      success: "#22c55e",
      warning: "#f59e0b",
      danger: "#ef4444",
    },
  },
  {
    id: "nordic_ice",
    name: "Nordic Ice",
    description: "Soguk, sade ve ferah acik-koyu hibrit tema.",
    mode: "light",
    category: "light",
    colors: {
      background: "#eaf2f8",
      surface: "#f8fafc",
      surface2: "#e2e8f0",
      border: "#94a3b8",
      text: "#0f172a",
      muted: "#475569",
      primary: "#0284c7",
      success: "#059669",
      warning: "#d97706",
      danger: "#dc2626",
    },
  },
  {
    id: "graphite_red",
    name: "Graphite Red",
    description: "Grafit siyah uzerine kirmizi vurgu.",
    mode: "dark",
    category: "dark",
    colors: {
      background: "#0a0a0a",
      surface: "#141414",
      surface2: "#1f1f1f",
      border: "#333333",
      text: "#f5f5f5",
      muted: "#a3a3a3",
      primary: "#ef4444",
      success: "#22c55e",
      warning: "#f59e0b",
      danger: "#dc2626",
    },
  },
  {
    id: "forest_command",
    name: "Forest Command",
    description: "Koyu yesil, saha operasyon ve dogal ton.",
    mode: "dark",
    category: "colorful",
    colors: {
      background: "#06100b",
      surface: "#0c1a12",
      surface2: "#13261b",
      border: "#214d35",
      text: "#f0fdf4",
      muted: "#86efac",
      primary: "#16a34a",
      success: "#22c55e",
      warning: "#eab308",
      danger: "#ef4444",
    },
  },
  {
    id: "ocean_depth",
    name: "Ocean Depth",
    description: "Koyu lacivert ve deniz mavisi odakli tema.",
    mode: "dark",
    category: "colorful",
    colors: {
      background: "#03121d",
      surface: "#071d2e",
      surface2: "#0b2a42",
      border: "#164e63",
      text: "#ecfeff",
      muted: "#67e8f9",
      primary: "#0891b2",
      success: "#10b981",
      warning: "#f59e0b",
      danger: "#f43f5e",
    },
  },
  {
    id: "royal_indigo",
    name: "Royal Indigo",
    description: "Mor-lacivert, prestijli ve premium tema.",
    mode: "dark",
    category: "premium",
    colors: {
      background: "#08071a",
      surface: "#111033",
      surface2: "#1c1a4d",
      border: "#3730a3",
      text: "#eef2ff",
      muted: "#a5b4fc",
      primary: "#6366f1",
      success: "#22c55e",
      warning: "#fbbf24",
      danger: "#fb7185",
    },
  },
  {
    id: "desert_sand",
    name: "Desert Sand",
    description: "Sicak, acik, bej ve kum tonlu sakin tema.",
    mode: "light",
    category: "light",
    colors: {
      background: "#f7f0e3",
      surface: "#fffaf0",
      surface2: "#efe1c6",
      border: "#d6bd8d",
      text: "#2f2415",
      muted: "#7c6a4c",
      primary: "#b45309",
      success: "#15803d",
      warning: "#d97706",
      danger: "#b91c1c",
    },
  },
  {
    id: "coffee_house",
    name: "Coffee House",
    description: "Kahverengi tonlarda sicak Çalışma temasi.",
    mode: "dark",
    category: "premium",
    colors: {
      background: "#120c08",
      surface: "#1d130c",
      surface2: "#2a1b12",
      border: "#4a2f1d",
      text: "#fff7ed",
      muted: "#c9a27d",
      primary: "#c08457",
      success: "#22c55e",
      warning: "#f59e0b",
      danger: "#ef4444",
    },
  },
  {
    id: "titanium",
    name: "Titanium",
    description: "Metalik gri, sade ve kurumsal tema.",
    mode: "dark",
    category: "dark",
    colors: {
      background: "#101214",
      surface: "#171a1d",
      surface2: "#22262a",
      border: "#3f464d",
      text: "#f4f4f5",
      muted: "#a1a1aa",
      primary: "#94a3b8",
      success: "#22c55e",
      warning: "#f59e0b",
      danger: "#ef4444",
    },
  },
  {
    id: "matrix_green",
    name: "Matrix Green",
    description: "Siyah zemin uzerinde canli yesil teknoloji temasi.",
    mode: "dark",
    category: "colorful",
    colors: {
      background: "#000000",
      surface: "#050a05",
      surface2: "#0a160a",
      border: "#14532d",
      text: "#dcfce7",
      muted: "#4ade80",
      primary: "#00ff66",
      success: "#22c55e",
      warning: "#fde047",
      danger: "#ef4444",
    },
  },
  {
    id: "rose_noir",
    name: "Rose Noir",
    description: "Koyu siyah ve rose/pembe premium tema.",
    mode: "dark",
    category: "premium",
    colors: {
      background: "#0c0508",
      surface: "#160b10",
      surface2: "#24111a",
      border: "#4a1d32",
      text: "#fff1f2",
      muted: "#f9a8d4",
      primary: "#ec4899",
      success: "#22c55e",
      warning: "#f59e0b",
      danger: "#f43f5e",
    },
  },
  {
    id: "arctic_light",
    name: "Arctic Light",
    description: "Temiz, beyaz-mavi, acik yönetici temasi.",
    mode: "light",
    category: "light",
    colors: {
      background: "#f1f8ff",
      surface: "#ffffff",
      surface2: "#e0f2fe",
      border: "#bae6fd",
      text: "#0c4a6e",
      muted: "#0369a1",
      primary: "#0284c7",
      success: "#16a34a",
      warning: "#ca8a04",
      danger: "#dc2626",
    },
  },
  {
    id: "paper_pro",
    name: "Paper Pro",
    description: "Sade beyaz, belge ve rapor odakli tema.",
    mode: "light",
    category: "premium",
    colors: {
      background: "#fafafa",
      surface: "#ffffff",
      surface2: "#f4f4f5",
      border: "#d4d4d8",
      text: "#18181b",
      muted: "#71717a",
      primary: "#52525b",
      success: "#16a34a",
      warning: "#d97706",
      danger: "#dc2626",
    },
  },
];

export const APP_THEME_IDS = APP_THEMES.map((theme) => theme.id);
export const LIGHT_THEME_IDS = APP_THEMES.filter(
  (theme) => theme.mode === "light",
).map((theme) => theme.id);

const APP_THEME_ID_SET = new Set<AppTheme>(APP_THEME_IDS);

export function isThemeId(value: string): value is AppTheme {
  return APP_THEME_ID_SET.has(value as AppTheme);
}

export function isLightTheme(themeId: AppTheme): boolean {
  return LIGHT_THEME_IDS.includes(themeId);
}
