import type { AppTheme } from "@/types";

export type ThemeMode = "dark" | "light";
export type ThemeCategory = "dark" | "light" | "colorful" | "premium";
export type ThemeFilter =
  | "all"
  | "dark"
  | "light"
  | "colorful"
  | "premium"
  | "simple";
export type ThemeTag = Exclude<ThemeFilter, "all">;

export interface ThemeDefinition {
  description: string;
  id: AppTheme;
  name: string;
  mode: ThemeMode;
  category: ThemeCategory;
  tags?: ThemeTag[];
  previewColors?: readonly string[];
  colors: {
    background: string;
    surface: string;
    surface2: string;
    border: string;
    text: string;
    muted: string;
    primary: string;
    success: string;
    warning: string;
    danger: string;
  };
}

export const DEFAULT_THEME_ID: AppTheme = "command_dark";

export const APP_THEMES: ThemeDefinition[] = [
  {
    id: "command_dark",
    name: "Command Dark",
    description: "Varsayilan koyu operasyon temasi.",
    mode: "dark",
    category: "dark",
    colors: {
      background: "#09090b",
      surface: "#111113",
      surface2: "#18181b",
      border: "#27272a",
      text: "#f4f4f5",
      muted: "#a1a1aa",
      primary: "#8b5cf6",
      success: "#22c55e",
      warning: "#f59e0b",
      danger: "#ef4444",
    },
  },
  {
    id: "midnight_violet",
    name: "Midnight Violet",
    description: "Daha mor, premium ve modern gorunum.",
    mode: "dark",
    category: "colorful",
    colors: {
      background: "#070514",
      surface: "#100b22",
      surface2: "#1b1235",
      border: "#34245f",
      text: "#f5f3ff",
      muted: "#c4b5fd",
      primary: "#a855f7",
      success: "#34d399",
      warning: "#fbbf24",
      danger: "#fb7185",
    },
  },
  {
    id: "obsidian_gold",
    name: "Obsidian Gold",
    description: "Siyah-altin yönetici paneli hissi.",
    mode: "dark",
    category: "premium",
    colors: {
      background: "#080706",
      surface: "#12100d",
      surface2: "#1c1710",
      border: "#3a2f1c",
      text: "#faf7ed",
      muted: "#c9b99a",
      primary: "#d4af37",
      success: "#22c55e",
      warning: "#f59e0b",
      danger: "#ef4444",
    },
  },
  {
    id: "slate_blue",
    name: "Slate Blue",
    description: "Daha kurumsal, soguk ve sade tema.",
    mode: "dark",
    category: "dark",
    colors: {
      background: "#0f172a",
      surface: "#111827",
      surface2: "#1e293b",
      border: "#334155",
      text: "#f8fafc",
      muted: "#94a3b8",
      primary: "#38bdf8",
      success: "#22c55e",
      warning: "#f59e0b",
      danger: "#f43f5e",
    },
  },
  {
    id: "executive_light",
    name: "Executive Light",
    description: "Gunduz kullanımi icin sade yönetici gorunumu.",
    mode: "light",
    category: "light",
    colors: {
      background: "#f8fafc",
      surface: "#ffffff",
      surface2: "#f1f5f9",
      border: "#cbd5e1",
      text: "#0f172a",
      muted: "#64748b",
      primary: "#4f46e5",
      success: "#16a34a",
      warning: "#d97706",
      danger: "#dc2626",
    },
  },
  {
    id: "emerald_terminal",
    name: "Emerald Terminal",
    description: "Siyah-yesil terminal ve hacker tarzi operasyon temasi.",
    mode: "dark",
    category: "colorful",
    colors: {
      background: "#020604",
      surface: "#07110c",
      surface2: "#0b1f14",
      border: "#164e2e",
      text: "#ecfdf5",
      muted: "#86efac",
      primary: "#22c55e",
      success: "#4ade80",
      warning: "#facc15",
      danger: "#f87171",
    },
  },
  {
    id: "cyber_neon",
    name: "Cyber Neon",
    description: "Neon mavi ve mor, modern teknoloji gorunumu.",
    mode: "dark",
    category: "colorful",
    colors: {
      background: "#050816",
      surface: "#0b1026",
      surface2: "#121a3d",
      border: "#263b80",
      text: "#eef2ff",
      muted: "#93c5fd",
      primary: "#06b6d4",
      success: "#10b981",
      warning: "#f59e0b",
      danger: "#fb7185",
    },
  },
  {
    id: "crimson_ops",
    name: "Crimson Ops",
    description: "Koyu kirmizi operasyon ve kriz yönetimi temasi.",
    mode: "dark",
    category: "colorful",
    colors: {
      background: "#0b0305",
      surface: "#16070a",
      surface2: "#240b10",
      border: "#4c121d",
      text: "#fff1f2",
      muted: "#fda4af",
      primary: "#e11d48",
      success: "#22c55e",
      warning: "#f59e0b",
      danger: "#ef4444",
    },
  },
  {
    id: "nordic_ice",
    name: "Nordic Ice",
    description: "Soguk, sade ve ferah acik-koyu hibrit tema.",
    mode: "light",
    category: "light",
    colors: {
      background: "#eaf2f8",
      surface: "#f8fafc",
      surface2: "#e2e8f0",
      border: "#94a3b8",
      text: "#0f172a",
      muted: "#475569",
      primary: "#0284c7",
      success: "#059669",
      warning: "#d97706",
      danger: "#dc2626",
    },
  },
  {
    id: "graphite_red",
    name: "Graphite Red",
    description: "Grafit siyah uzerine kirmizi vurgu.",
    mode: "dark",
    category: "dark",
    colors: {
      background: "#0a0a0a",
      surface: "#141414",
      surface2: "#1f1f1f",
      border: "#333333",
      text: "#f5f5f5",
      muted: "#a3a3a3",
      primary: "#ef4444",
      success: "#22c55e",
      warning: "#f59e0b",
      danger: "#dc2626",
    },
  },
  {
    id: "forest_command",
    name: "Forest Command",
    description: "Koyu yesil, saha operasyon ve dogal ton.",
    mode: "dark",
    category: "colorful",
    colors: {
      background: "#06100b",
      surface: "#0c1a12",
      surface2: "#13261b",
      border: "#214d35",
      text: "#f0fdf4",
      muted: "#86efac",
      primary: "#16a34a",
      success: "#22c55e",
      warning: "#eab308",
      danger: "#ef4444",
    },
  },
  {
    id: "ocean_depth",
    name: "Ocean Depth",
    description: "Koyu lacivert ve deniz mavisi odakli tema.",
    mode: "dark",
    category: "colorful",
    colors: {
      background: "#03121d",
      surface: "#071d2e",
      surface2: "#0b2a42",
      border: "#164e63",
      text: "#ecfeff",
      muted: "#67e8f9",
      primary: "#0891b2",
      success: "#10b981",
      warning: "#f59e0b",
      danger: "#f43f5e",
    },
  },
  {
    id: "royal_indigo",
    name: "Royal Indigo",
    description: "Mor-lacivert, prestijli ve premium tema.",
    mode: "dark",
    category: "premium",
    colors: {
      background: "#08071a",
      surface: "#111033",
      surface2: "#1c1a4d",
      border: "#3730a3",
      text: "#eef2ff",
      muted: "#a5b4fc",
      primary: "#6366f1",
      success: "#22c55e",
      warning: "#fbbf24",
      danger: "#fb7185",
    },
  },
  {
    id: "desert_sand",
    name: "Desert Sand",
    description: "Sicak, acik, bej ve kum tonlu sakin tema.",
    mode: "light",
    category: "light",
    colors: {
      background: "#f7f0e3",
      surface: "#fffaf0",
      surface2: "#efe1c6",
      border: "#d6bd8d",
      text: "#2f2415",
      muted: "#7c6a4c",
      primary: "#b45309",
      success: "#15803d",
      warning: "#d97706",
      danger: "#b91c1c",
    },
  },
  {
    id: "coffee_house",
    name: "Coffee House",
    description: "Kahverengi tonlarda sicak Çalışma temasi.",
    mode: "dark",
    category: "premium",
    colors: {
      background: "#120c08",
      surface: "#1d130c",
      surface2: "#2a1b12",
      border: "#4a2f1d",
      text: "#fff7ed",
      muted: "#c9a27d",
      primary: "#c08457",
      success: "#22c55e",
      warning: "#f59e0b",
      danger: "#ef4444",
    },
  },
  {
    id: "titanium",
    name: "Titanium",
    description: "Metalik gri, sade ve kurumsal tema.",
    mode: "dark",
    category: "dark",
    colors: {
      background: "#101214",
      surface: "#171a1d",
      surface2: "#22262a",
      border: "#3f464d",
      text: "#f4f4f5",
      muted: "#a1a1aa",
      primary: "#94a3b8",
      success: "#22c55e",
      warning: "#f59e0b",
      danger: "#ef4444",
    },
  },
  {
    id: "matrix_green",
    name: "Matrix Green",
    description: "Siyah zemin uzerinde canli yesil teknoloji temasi.",
    mode: "dark",
    category: "colorful",
    colors: {
      background: "#000000",
      surface: "#050a05",
      surface2: "#0a160a",
      border: "#14532d",
      text: "#dcfce7",
      muted: "#4ade80",
      primary: "#00ff66",
      success: "#22c55e",
      warning: "#fde047",
      danger: "#ef4444",
    },
  },
  {
    id: "rose_noir",
    name: "Rose Noir",
    description: "Koyu siyah ve rose/pembe premium tema.",
    mode: "dark",
    category: "premium",
    colors: {
      background: "#0c0508",
      surface: "#160b10",
      surface2: "#24111a",
      border: "#4a1d32",
      text: "#fff1f2",
      muted: "#f9a8d4",
      primary: "#ec4899",
      success: "#22c55e",
      warning: "#f59e0b",
      danger: "#f43f5e",
    },
  },
  {
    id: "arctic_light",
    name: "Arctic Light",
    description: "Temiz, beyaz-mavi, acik yönetici temasi.",
    mode: "light",
    category: "light",
    colors: {
      background: "#f1f8ff",
      surface: "#ffffff",
      surface2: "#e0f2fe",
      border: "#bae6fd",
      text: "#0c4a6e",
      muted: "#0369a1",
      primary: "#0284c7",
      success: "#16a34a",
      warning: "#ca8a04",
      danger: "#dc2626",
    },
  },
  {
    id: "paper_pro",
    name: "Paper Pro",
    description: "Sade beyaz, belge ve rapor odakli tema.",
    mode: "light",
    category: "premium",
    colors: {
      background: "#fafafa",
      surface: "#ffffff",
      surface2: "#f4f4f5",
      border: "#d4d4d8",
      text: "#18181b",
      muted: "#71717a",
      primary: "#52525b",
      success: "#16a34a",
      warning: "#d97706",
      danger: "#dc2626",
    },
  },
  {
    id: "royal-amethyst",
    name: "Royal Amethyst",
    description: "Derin ametist tonlarında seçkin yönetici çalışma alanı.",
    mode: "dark",
    category: "premium",
    tags: ["dark", "premium"],
    colors: {
      background: "#080512",
      surface: "#120b22",
      surface2: "#1d1233",
      border: "#49336f",
      text: "#faf7ff",
      muted: "#b9a7d3",
      primary: "#9b5de5",
      success: "#34d399",
      warning: "#f4b942",
      danger: "#fb7185",
    },
  },
  {
    id: "carbon-mint",
    name: "Carbon Mint",
    description: "Karbon siyahı yüzeylerde dengeli mint vurgular.",
    mode: "dark",
    category: "colorful",
    tags: ["dark", "colorful"],
    colors: {
      background: "#070a09",
      surface: "#0e1412",
      surface2: "#17201d",
      border: "#2b3a35",
      text: "#eefbf6",
      muted: "#91a9a0",
      primary: "#2dd4a7",
      success: "#34d399",
      warning: "#fbbf24",
      danger: "#fb7185",
    },
  },
  {
    id: "deep-space",
    name: "Deep Space",
    description: "Koyu lacivert tonlarla sakin ve odaklı minimal görünüm.",
    mode: "dark",
    category: "dark",
    tags: ["dark", "simple"],
    colors: {
      background: "#050914",
      surface: "#0a1120",
      surface2: "#111b30",
      border: "#243450",
      text: "#eef4ff",
      muted: "#8fa3bf",
      primary: "#4f8cff",
      success: "#34d399",
      warning: "#fbbf24",
      danger: "#fb7185",
    },
  },
  {
    id: "coffee-bronze",
    name: "Coffee Bronze",
    description: "Koyu kahve yüzey ve bronz vurguyla sıcak profesyonel tema.",
    mode: "dark",
    category: "premium",
    tags: ["dark", "premium"],
    colors: {
      background: "#100a07",
      surface: "#1b120d",
      surface2: "#281a12",
      border: "#553a25",
      text: "#fff7ed",
      muted: "#c9a788",
      primary: "#c0834d",
      success: "#3fbf7f",
      warning: "#e8a43a",
      danger: "#e96f62",
    },
  },
  {
    id: "arctic-glass",
    name: "Arctic Glass",
    description: "Buz beyazı ve yumuşak mavi-gri tonlarda ferah çalışma alanı.",
    mode: "light",
    category: "light",
    tags: ["light", "simple"],
    colors: {
      background: "#eff6fb",
      surface: "#ffffff",
      surface2: "#e6f0f7",
      border: "#bfd0dc",
      text: "#14212b",
      muted: "#60717e",
      primary: "#4f86a6",
      success: "#16835b",
      warning: "#b66a16",
      danger: "#c43d4f",
    },
  },
  {
    id: "night-sakura",
    name: "Night Sakura",
    description: "Gece yüzeylerinde modern ve yumuşak sakura pembesi.",
    mode: "dark",
    category: "colorful",
    tags: ["dark", "colorful"],
    colors: {
      background: "#10070d",
      surface: "#1a0d16",
      surface2: "#291323",
      border: "#56203f",
      text: "#fff1f7",
      muted: "#d8a0bc",
      primary: "#f05a9d",
      success: "#35c58a",
      warning: "#f5b94c",
      danger: "#f06476",
    },
  },
  {
    id: "military-olive",
    name: "Military Olive",
    description: "Taktik zeytin tonlarında ciddi ve sade operasyon teması.",
    mode: "dark",
    category: "dark",
    tags: ["dark", "simple"],
    colors: {
      background: "#0c0e08",
      surface: "#15190f",
      surface2: "#202719",
      border: "#414a31",
      text: "#f2f4e8",
      muted: "#aeb79a",
      primary: "#8da34f",
      success: "#65a955",
      warning: "#d2a640",
      danger: "#d86458",
    },
  },
  {
    id: "ice-lavender",
    name: "Ice Lavender",
    description: "Açık lavanta yüzeylerle sakin ve premium çalışma alanı.",
    mode: "light",
    category: "premium",
    tags: ["light", "premium"],
    colors: {
      background: "#f5f2fb",
      surface: "#ffffff",
      surface2: "#ece7f6",
      border: "#d1c7e2",
      text: "#261d35",
      muted: "#716582",
      primary: "#8066b3",
      success: "#21855d",
      warning: "#b86b1d",
      danger: "#c4475a",
    },
  },
  {
    id: "graphite-cyan",
    name: "Graphite Cyan",
    description: "Grafit yüzeylerde teknik, dengeli ve premium camgöbeği.",
    mode: "dark",
    category: "colorful",
    tags: ["dark", "colorful"],
    colors: {
      background: "#080b0d",
      surface: "#101619",
      surface2: "#192327",
      border: "#30434a",
      text: "#effcff",
      muted: "#91aeb8",
      primary: "#22c7d6",
      success: "#39c58a",
      warning: "#efb64a",
      danger: "#f06b75",
    },
  },
  {
    id: "sandstone-light",
    name: "Sandstone Light",
    description: "Sıcak kum tonlarında okunaklı ve sade günlük çalışma alanı.",
    mode: "light",
    category: "light",
    tags: ["light", "simple"],
    colors: {
      background: "#f5efe5",
      surface: "#fffaf2",
      surface2: "#ece1d2",
      border: "#d3c1aa",
      text: "#2d261f",
      muted: "#746657",
      primary: "#a26b3f",
      success: "#397b4d",
      warning: "#b66c21",
      danger: "#b94747",
    },
  },
  {
    id: "ruby-noir",
    name: "Ruby Noir",
    description: "Siyah kiraz yüzeylerde güçlü ve seçkin yakut vurgusu.",
    mode: "dark",
    category: "premium",
    tags: ["dark", "premium"],
    colors: {
      background: "#0b0508",
      surface: "#160a10",
      surface2: "#241019",
      border: "#552038",
      text: "#fff2f5",
      muted: "#d5a1ad",
      primary: "#d63b62",
      success: "#36b77d",
      warning: "#e4a43d",
      danger: "#f05c6c",
    },
  },
  {
    id: "azure-command",
    name: "Azure Command",
    description: "Derin mavi komuta yüzeylerinde dengeli azure vurgular.",
    mode: "dark",
    category: "colorful",
    tags: ["dark", "colorful"],
    colors: {
      background: "#050b18",
      surface: "#0b1428",
      surface2: "#11213c",
      border: "#274b78",
      text: "#f0f7ff",
      muted: "#91acd0",
      primary: "#2587e8",
      success: "#37bd86",
      warning: "#eeb64b",
      danger: "#ef6573",
    },
  },
  {
    id: "pearl-minimal",
    name: "Pearl Minimal",
    description: "İnci beyazı tonlarda sakin ve dikkat dağıtmayan çalışma alanı.",
    mode: "light",
    category: "light",
    tags: ["light", "simple"],
    colors: {
      background: "#f7f7f5",
      surface: "#ffffff",
      surface2: "#efefec",
      border: "#d7d8d3",
      text: "#20231f",
      muted: "#6d746b",
      primary: "#6b7c73",
      success: "#2d8055",
      warning: "#ad681c",
      danger: "#bd4350",
    },
  },
  {
    id: "solar-amber",
    name: "Solar Amber",
    description: "Koyu zeminde kontrollü amber enerjisi ve sıcak vurgu.",
    mode: "dark",
    category: "colorful",
    tags: ["dark", "colorful"],
    colors: {
      background: "#0e0903",
      surface: "#181007",
      surface2: "#26190b",
      border: "#563817",
      text: "#fff7e6",
      muted: "#c9a66d",
      primary: "#f2a51a",
      success: "#46b97b",
      warning: "#f6c453",
      danger: "#e86a5c",
    },
  },
  {
    id: "titanium-blue",
    name: "Titanium Blue",
    description: "Titanyum gri ve çelik mavisiyle sade kurumsal görünüm.",
    mode: "dark",
    category: "dark",
    tags: ["dark", "simple"],
    colors: {
      background: "#0c1015",
      surface: "#141a21",
      surface2: "#1e2731",
      border: "#3a4858",
      text: "#f1f5f9",
      muted: "#9eacbb",
      primary: "#5f8fbf",
      success: "#42b883",
      warning: "#dfaa47",
      danger: "#df6671",
    },
  },
  {
    id: "velvet-plum",
    name: "Velvet Plum",
    description: "Zengin erik tonlarında yumuşak ve lüks yönetim ekranı.",
    mode: "dark",
    category: "premium",
    tags: ["dark", "premium"],
    colors: {
      background: "#0e0710",
      surface: "#1a0d1c",
      surface2: "#28142b",
      border: "#56305c",
      text: "#fff3ff",
      muted: "#cda9cf",
      primary: "#a85eb5",
      success: "#42bd86",
      warning: "#e6ad4a",
      danger: "#e8667d",
    },
  },
  {
    id: "glacier-mint",
    name: "Glacier Mint",
    description: "Serin açık yüzeylerde temiz ve sakin mint vurgusu.",
    mode: "light",
    category: "light",
    tags: ["light", "simple"],
    colors: {
      background: "#eef8f6",
      surface: "#ffffff",
      surface2: "#e1f1ed",
      border: "#b9d7cf",
      text: "#16312c",
      muted: "#5e7771",
      primary: "#2f9d83",
      success: "#21815f",
      warning: "#ae6e20",
      danger: "#c04454",
    },
  },
  {
    id: "neon-orchid",
    name: "Neon Orchid",
    description: "Kontrollü orkide neonuyla modern ve teknik çalışma alanı.",
    mode: "dark",
    category: "colorful",
    tags: ["dark", "colorful"],
    colors: {
      background: "#09050f",
      surface: "#140b20",
      surface2: "#211132",
      border: "#482565",
      text: "#fbf2ff",
      muted: "#c5a0d8",
      primary: "#c24ef0",
      success: "#3fc48a",
      warning: "#eeb449",
      danger: "#f16582",
    },
  },
  {
    id: "walnut-cream",
    name: "Walnut Cream",
    description: "Sıcak krem yüzey ve ceviz kontrastıyla rahat okunabilirlik.",
    mode: "light",
    category: "light",
    tags: ["light", "simple"],
    colors: {
      background: "#f7f0e5",
      surface: "#fffaf2",
      surface2: "#ecdfcf",
      border: "#cfbda8",
      text: "#30271f",
      muted: "#756556",
      primary: "#8a5a38",
      success: "#397c50",
      warning: "#ad671d",
      danger: "#b94747",
    },
  },
  {
    id: "storm-indigo",
    name: "Storm Indigo",
    description: "Fırtınalı indigo tonlarında odaklı premium komuta ekranı.",
    mode: "dark",
    category: "premium",
    tags: ["dark", "premium"],
    colors: {
      background: "#070915",
      surface: "#101426",
      surface2: "#191f38",
      border: "#343f67",
      text: "#f2f4ff",
      muted: "#9da7ca",
      primary: "#6574d9",
      success: "#3dba82",
      warning: "#e6ad48",
      danger: "#e75f72",
    },
  },
  {
    id: "matrix-lime",
    name: "Matrix Lime",
    description: "Terminal koyuluğunda canlı fakat dengeli lime vurgusu.",
    mode: "dark",
    category: "colorful",
    tags: ["dark", "colorful"],
    colors: {
      background: "#030603",
      surface: "#081008",
      surface2: "#102010",
      border: "#285229",
      text: "#efffe9",
      muted: "#91c785",
      primary: "#84e34d",
      success: "#5fd36b",
      warning: "#e4c64d",
      danger: "#ed6b68",
    },
  },
  {
    id: "cloud-silver",
    name: "Cloud Silver",
    description: "Gümüş beyazı tonlarda temiz ve kurumsal çalışma alanı.",
    mode: "light",
    category: "light",
    tags: ["light", "simple"],
    colors: {
      background: "#f3f5f7",
      surface: "#ffffff",
      surface2: "#e8ecef",
      border: "#c9d0d6",
      text: "#1e252b",
      muted: "#65717b",
      primary: "#667c8c",
      success: "#2b8059",
      warning: "#ad681f",
      danger: "#c04452",
    },
  },
  {
    id: "crimson-executive",
    name: "Crimson Executive",
    description: "Koyu yönetici kırmızısıyla ciddi ve güçlü premium arayüz.",
    mode: "dark",
    category: "premium",
    tags: ["dark", "premium"],
    colors: {
      background: "#0c0506",
      surface: "#180a0c",
      surface2: "#251013",
      border: "#572129",
      text: "#fff2f3",
      muted: "#d0a0a5",
      primary: "#bd3345",
      success: "#3ab47a",
      warning: "#e4aa43",
      danger: "#ef5966",
    },
  },
  {
    id: "oceanic-teal",
    name: "Oceanic Teal",
    description: "Okyanus derinliği ve teal odak rengiyle dengeli teknoloji teması.",
    mode: "dark",
    category: "colorful",
    tags: ["dark", "colorful"],
    colors: {
      background: "#041012",
      surface: "#081b1e",
      surface2: "#0d292d",
      border: "#1e5157",
      text: "#edffff",
      muted: "#86b9bd",
      primary: "#1ca7a8",
      success: "#36bd83",
      warning: "#e7b348",
      danger: "#e8666f",
    },
  },
  {
    id: "desert-night",
    name: "Desert Night",
    description: "Koyu çöl kahvesinde sıcak ve sade operasyon paneli.",
    mode: "dark",
    category: "dark",
    tags: ["dark", "simple"],
    colors: {
      background: "#0e0a07",
      surface: "#18110d",
      surface2: "#241a13",
      border: "#4a392b",
      text: "#f7eee5",
      muted: "#b8a28f",
      primary: "#a8794f",
      success: "#4aaf79",
      warning: "#dda847",
      danger: "#dd685d",
    },
  },
];

export const APP_THEME_IDS = APP_THEMES.map((theme) => theme.id);
export const NEW_THEME_IDS: AppTheme[] = [
  "royal-amethyst",
  "carbon-mint",
  "deep-space",
  "coffee-bronze",
  "arctic-glass",
  "night-sakura",
  "military-olive",
  "ice-lavender",
  "graphite-cyan",
  "sandstone-light",
  "ruby-noir",
  "azure-command",
  "pearl-minimal",
  "solar-amber",
  "titanium-blue",
  "velvet-plum",
  "glacier-mint",
  "neon-orchid",
  "walnut-cream",
  "storm-indigo",
  "matrix-lime",
  "cloud-silver",
  "crimson-executive",
  "oceanic-teal",
  "desert-night",
];
export const LIGHT_THEME_IDS = APP_THEMES.filter(
  (theme) => theme.mode === "light",
).map((theme) => theme.id);

const APP_THEME_MAP = new Map(
  APP_THEMES.map((theme) => [theme.id, theme] as const),
);
const APP_THEME_ID_SET = new Set<AppTheme>(APP_THEME_IDS);

export function getThemeById(themeId: AppTheme): ThemeDefinition | undefined {
  return APP_THEME_MAP.get(themeId);
}

export function isThemeId(value: string): value is AppTheme {
  return APP_THEME_ID_SET.has(value as AppTheme);
}

export function isLightTheme(themeId: AppTheme): boolean {
  return LIGHT_THEME_IDS.includes(themeId);
}

export function isNewThemeId(themeId: AppTheme): boolean {
  return NEW_THEME_IDS.includes(themeId);
}

export function getThemeTags(theme: ThemeDefinition): ThemeTag[] {
  if (theme.tags) return theme.tags;

  const styleTag: ThemeTag =
    theme.category === "colorful" || theme.category === "premium"
      ? theme.category
      : "simple";

  return [theme.mode, styleTag];
}

export function getThemePreviewColors(
  theme: ThemeDefinition,
): readonly string[] {
  return (
    theme.previewColors ?? [
      theme.colors.background,
      theme.colors.surface,
      theme.colors.primary,
      theme.colors.success,
    ]
  ).slice(0, 4);
}
